### ISSUE TITLE
How display a gallery

### ISSUE THREAD

**Issue by artmaug** [zastrich/cfs-gallery#1]
Hi, thanks for the plugin.
I would like to know how to display the gallery, I searched and could not find this information.
Thank you very much for the support.

**Comment by zastrich** [comment]
### Code example:

`
/*Return Array of Images IDs*/
$Images = CFS()->get("gallery");

/*Verify array not empty*/
if(is_array($Images) && sizeof($Images) > 0)
foreach($Images as $Key => $ImageID){
	/*Populate $Image */
	$Image = get_post($ImageID);
	?>
	<div class="item">
		<a href="<?=@array_shift(wp_get_attachment_image_src($Image->ID, "full"))?>">
			<img src="<?=@array_shift(wp_get_attachment_image_src($Image->ID, "large"))?>);" alt="<?=$Image->post_title?>" />
		</a>
	</div>
<?php 
}
`

**Comment by zastrich** [comment]
### Code example:

```
$Images = CFS()->get("gallery"); /* Return array of Image IDs */
		
if(is_array($Images) && sizeof($Images) > 0)
foreach($Images as $ImageID){
	$Image = get_post($ImageID); /* Get properties of image post by ID */
	?>
	<a href="<?=@array_shift(wp_get_attachment_image_src($ImageID, "full"))?>">
		<img src="<?=@array_shift(wp_get_attachment_image_src($ImageID, "large"))?>" alt="<?=$Image->post_content?>">
	</a>
	<?php 
}
```

**Comment by artmaug** [comment]
Thanks a lot, works perfect!
Really great plugin!
